version: 0.0
os: linux
files:
  - source: /
    destination: /root/projects/pipeline
permissions:
  - object: /root/projects/pipeline
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 10
      runas: ec2-user
  DownloadBundle:
    - location: scripts/downloadBundle.sh
      timeout: 10
      runas: ec2-user
  Install:
    - location: scripts/install.sh
      timeout: 10
      runas: ec2-user
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 10
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 10
      runas: ec2-user
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 10
      runas: ec2-user
  ValidateService:
    - location: scripts/validateService.sh
      timeout: 10
      runas: ec2-user
