version: 0.0
os: linux
files:
  - source: /
    destination: projects/pipeline
permissions:
  - object: projects/pipeline
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# hooks:
#   BeforeInstall:
#     - location: scripts/beforeInstall.sh
#       timeout: 10
#       runas: ec2-user
#   ApplicationStart:
#     - location: scripts/applicationStart.sh
#       timeout: 10
#       runas: ec2-user
