version: 0.0
os: linux
files:
  - source: /
    destination: /projects/pipeline/dara
    file_exists_behavior: OVERWRITE
permissions:
  - object: /ec2-user/projects/pipeline/dara
    pattern: "**"
    owner: root
    group: root
# hooks:
#   BeforeInstall:
#     - location: scripts/beforeInstall.sh
#       timeout: 10
#       runas: root
#   ApplicationStart:
#     - location: scripts/applicationStart.sh
#       timeout: 10
#       runas: root
