version: 0.0
os: linux
files:
  - source: /dist
    destination: /home/ec2-user/projects/pipeline/dist
    file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/projects/pipeline/dist
    pattern: "**"
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 10
      runas: root
